server:
  port: 10011
  max-http-header-size: 8192
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 10003
        dashboard: sentinel.stalary.com
  zipkin:
    base-url: 127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0

