server:
  debug: true
  port: 10015
  max-http-header-size: 8192
  user: 127.0.0.1:7100
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 10003
        dashboard: sentinel.stalary.com
  zipkin:
    base-url: 127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 127.0.0.1:9300
logging:
  level:
    com.stalary.pf.user.client: DEBUG # feign日志
