server:
  port: 10000
  user: 127.0.0.1:7100
  max-http-header-size: 8192
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  zipkin:
    base-url: 127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.gateway.client: DEBUG # feign日志
    com.alibaba.nacos.client.naming: WARN