server:
  port: 10014
  max-http-header-size: 8192
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:
    base-url: 127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.consumer.client: DEBUG # feign日志
com:
  stalary:
    lightmq:
      consumer: true
      order: true
      group: master
      auto: true
      url: http://localhost:8001